# -*- coding: utf-8 -*-
"""etl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ve0KaQ6ugcIVAqiXj0Jwt4tU_p5Xu9e
"""

import pandas as pd

raw_header = pd.read_csv("daily_temperature_1000_cities_1980_2020.csv", skiprows=1, nrows=1, header=None)
city_names = raw_header.iloc[0, 1:].tolist()

df = pd.read_csv("daily_temperature_1000_cities_1980_2020.csv", skiprows=6, low_memory=False)

df.columns = ['date'] + city_names

# Select only the desired cities
selected_cities = ['New York', 'Los Angeles', 'Tokyo']
df = df[['date'] + selected_cities]

# Convert from wide to long format
melted_df = df.melt(id_vars=['date'], var_name='city', value_name='temperature')


# Clean
melted_df = melted_df[melted_df['temperature'].notnull()]
melted_df['temperature'] = pd.to_numeric(melted_df['temperature'], errors='coerce')
melted_df = melted_df.dropna()

melted_df.to_csv('cleaned_weather.csv', index=False)


print(melted_df.head())

from google.colab import files
files.download('cleaned_weather.csv')

